print("******************")
print("Hamburguesas el corral")
print("******************")
nombreUsuario=input("digite el nombre del usuario:")
cedulaUsuario=input("digite el numero de documento:")
pedidoUsuario=input("Que hamburguesa va a ordenar:")
valorPedido=int(input("valor de pedido:"))
cantidadPedido=int(input("Cantidad de hamburguesas a pedir:"))
print("******************")
print("******************")
print("******************")

print(pedidoUsuario)
print(cantidadPedido)
print(valorPedido*cantidadPedido)
